package mitl.IntoTheHeaven.application.dto;

import lombok.Builder;
import lombok.Getter;
import mitl.IntoTheHeaven.domain.enums.MediaType;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Application layer DTO for presigned upload information
 * Contains data generated by CloudflareR2Port for direct uploads
 */
@Getter
@Builder
public class PresignedUploadInfo {

    private final List<UploadItem> uploads;
    private final LocalDateTime expiresAt;

    @Getter
    @Builder
    public static class UploadItem {
        private final MediaType mediaType;
        private final String uploadId;
        private final String uploadUrl;
        private final String publicUrl;
        private final String method;
        private final Long maxFileSize;
    }

    /**
     * Create from upload items and expiration time
     */
    public static PresignedUploadInfo of(List<UploadItem> uploads, LocalDateTime expiresAt) {
        return PresignedUploadInfo.builder()
                .uploads(uploads)
                .expiresAt(expiresAt)
                .build();
    }
}
