name: CI/CD

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch build)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define image tags
        id: meta
        run: |
          echo "IMAGE=${{ secrets.DOCKER_IMAGE }}" >> $GITHUB_OUTPUT
          echo "TAG_SHA=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "TAG_LATEST=latest" >> $GITHUB_OUTPUT



      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64/v8
          tags: |
            ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.TAG_SHA }}
            ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.TAG_LATEST }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Self-Hosted
    needs: build_and_push
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set DOCKER_CONFIG env for this job
        run: echo "DOCKER_CONFIG=$PWD/.docker" >> $GITHUB_ENV

      - name: Prepare Docker config (avoid macOS keychain prompt)
        run: |
          mkdir -p "$DOCKER_CONFIG"
          echo '{}' > "$DOCKER_CONFIG/config.json"

      - name: Inject Docker auth to config.json (no keychain)
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          AUTH=$(printf "%s" "$DOCKERHUB_USERNAME:$DOCKERHUB_TOKEN" | base64)
          jq -n --arg auth "$AUTH" '{auths:{"https://index.docker.io/v1/":{"auth":$auth}}}' > "$DOCKER_CONFIG/config.json"
          cat "$DOCKER_CONFIG/config.json"

      - name: Detect compose command
        run: |
          if docker compose version >/dev/null 2>&1; then
            echo "COMPOSE=docker compose" >> $GITHUB_ENV
          elif command -v docker-compose >/dev/null 2>&1; then
            echo "COMPOSE=docker-compose" >> $GITHUB_ENV
          else
            echo "Docker Compose not found" >&2
            exit 1
          fi

      - name: Create .env from secrets
        run: |
          cat > .env << 'EOF'
          # Generated by GitHub Actions
          APP_IMAGE=${{ secrets.DOCKER_IMAGE }}:${{ github.sha }}
          SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS=${{ secrets.JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS }}
          EOF

      - name: Pull image
        run: $COMPOSE pull app | cat

      - name: Start/Update service
        run: $COMPOSE up -d app | cat

      - name: Cleanup dangling images
        run: docker image prune -f | cat

